### PR TITLE
Predictive Model based on Neural Net

### PR DESCRIPTION
**Pull request by 0xastro**
This Model is consisted of 2 nodes:

1. `CE_Predictive_Node` :
based on Neural Network, it senses 3 channels simultenously at the spectrum Band 800MHz at _**fc**_=833e6 and _**B.W**_=13e6, then pass the measured features to the Neural Network to make a prediction indicates channels status.

2. `CE_Random_Behaviour_PU`:
generates a random channel to operate on it **_[CHANNEL1, CHANNEL2, CHANNEL3]_** without any predetermined probabilities using the standard rand() method for generating random integers and then divides by the maximum number that can be generated which is 3.

[Scenario Demo](https://youtu.be/QdT6wcxbOYQ)

### CODE REVIEW

**Comment by ericps1** [comment]
Hi, thanks for the contribution. The demo looked pretty cool. Would you mind updating the crts/scenarios/README.md file to include the scenario you've added?

**Comment by 0xastro** [comment]
Done.

2017-07-01 23:54 GMT+02:00 ericps1 <notifications@github.com>:

**Comment by 0xastro** [comment]
Shall I update the makefile?

2017-07-01 23:54 GMT+02:00 ericps1 <notifications@github.com>:

**Comment by ericps1** [comment]
Great, thanks!

**Pull request merged**
